# SciPy

# Numpy
- 패키지 사용 이전에 반드시 **import**해야 하는 것을 기억해주세요!
- Numpy의 함수를 사용할 때마다 "numpy"를 적는 것이 귀찮기 때문에, 흔히들 "**np**"로 줄여서 import합니다.

In [1]:
import numpy as np

## array
- array는 numpy에서 제공하는 자료구조로, 파이썬의 list와 유사한 성격을 보입니다.
- MATLAB, R에서의 벡터, 행렬 연산 인터페이스와 거의 같은 기능을 제공합니다.

In [2]:
# Rank = 1인 array
a = np.array((1,2,3,4))
print(a)
print(type(a))
print(a.shape)

# Rank = 2인 array
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))
print(b.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [3]:
# array의 성분은 모두 index를 갖고 있습니다. 이를 이용하여 성분을 바꿀 수 있습니다.
a = np.array([1,2,3,4])
print(a[0], a[1])
a[0] = 5 # array의 가장 첫 번째 성분을 5로 변경
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b[0]) # b 배열의 첫 번째 행을 출력
print(b[0][2]) # b 배열의 첫 번째 행, 세 번째 열의 값을 출력 (즉, 행렬의 (1,3) 성분)
print(b[0,2])  # 위와 동일
b[0,2] = 7
print(b)

1 2
[5 2 3 4]
[1 2 3]
3
3
[[1 2 7]
 [4 5 6]]


In [4]:
# array 성분의 type을 정의할 수 있습니다.
a = np.array([1,2,3,4], float)
print(a)
print(type(a[0]))
print(a.dtype)

b = np.array([1,2,3,4], int)
print(b)
print(type(b[0]))
print(b.dtype)

[ 1.  2.  3.  4.]
<class 'numpy.float64'>
float64
[1 2 3 4]
<class 'numpy.int64'>
int64


In [5]:
# MATLAB, R과 유사한 인터페이스로 행렬의 성분들을 분해할 수 있습니다.
a = np.array([[1,2,3,], [4,5,6]])
print(a[0,0]) # a 행렬의 (1,1) 성분
print(a[0,:]) # a 행렬의 첫 번째 행
print(a[:,2]) # a 행렬의 세 번째 열

1
[1 2 3]
[3 6]


In [6]:
mylist = [[1, 2, 3], [3, 4, 5]]
myarray = np.array(mylist)
print(myarray)
print(myarray.shape)
print("First row: %s" % myarray[0])
print("Last row: %s" % myarray[-1])
print("Specific row and col: %s" % myarray[0, 2])
print("Whole col: %s" % myarray[:,2])

[[1 2 3]
 [3 4 5]]
(2, 3)
First row: [1 2 3]
Last row: [3 4 5]
Specific row and col: 3
Whole col: [3 5]


## array 연산
- array 연산 역시 MATLAB, R과 매우 유사합니다.
- +, -, /, //, %, ** 등 기본적인 파이썬의 연산자는 그대로 적용 가능합니다.
- numpy 자체에서 abs, sign, sqrt, log, log10, exp, sin, cos, tan, floor(내림), ceil(올림), rint(반올림) 등의 함수를 제공합니다.

In [7]:
a = np.array([1, 2])
b = np.array([5, 6])

a + b

array([6, 8])

In [8]:
# Python의 기본 연산자에 대해서 우리가 생각하는대로 결과가 나옵니다.
a = np.array([1,2,3])
b = np.array([2,5,6])

print(a + b)
print(a - b)
print(a / b)
print(b / a)
print(b // a)
print(b % a)
print(a ** b)

[3 7 9]
[-1 -3 -3]
[ 0.5  0.4  0.5]
[ 2.   2.5  2. ]
[2 2 2]
[0 1 0]
[  1  32 729]


In [11]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,4,6],[6,8,10]])

print(a + b)
print(a - b)
print(a / b)
print(b / a)
print(b // a)
print(b % a)
print(a ** b)

[[ 3  6  9]
 [10 13 16]]
[[-1 -2 -3]
 [-2 -3 -4]]
[[ 0.5         0.5         0.5       ]
 [ 0.66666667  0.625       0.6       ]]
[[ 2.          2.          2.        ]
 [ 1.5         1.6         1.66666667]]
[[2 2 2]
 [1 1 1]]
[[0 0 0]
 [2 3 4]]
[[       1       16      729]
 [    4096   390625 60466176]]


In [9]:
# array들의 차원의 사이즈가 다르면, 에러메시지가 나타납니다.
a = np.array([1,2,3])
b = np.array([3,4])

print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [13]:
# 그러나 다차원의 배열과 일차원의 배열을 더하는 경우,
# numpy에서 (알아서) 차원을 맞춰서 더하게 됩니다.
# Numpy의 공식 문서에서는 이를 "broadcasting"한다고 표현하고 있습니다.
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([0.1, 0.2])
print(a)
print(b)
print(a + b)

[[1 2]
 [3 4]
 [5 6]]
[ 0.1  0.2]
[[ 1.1  2.2]
 [ 3.1  4.2]
 [ 5.1  6.2]]


In [14]:
# 2 by 2 행렬에 2 by 1의 벡터를 연산하는 경우
a = np.zeros((2,2)) # 모든 성분이 0이고 크기가 2 by 2인 행렬을 생성
b = np.array([2,3])
print(a)
print(b)
print(a + b)

# Numpy의 newaxis라는 함수를 이용하여, b를 어떤 방향으로 더할지 정의할 수 있습니다.
print(a + b[np.newaxis,:]) # b를 a의 행에 각각 더할 때,
print(a + b[:,np.newaxis]) # b를 a의 열에 각각 더할 때,

[[ 0.  0.]
 [ 0.  0.]]
[2 3]
[[ 2.  3.]
 [ 2.  3.]]
[[ 2.  3.]
 [ 2.  3.]]
[[ 2.  2.]
 [ 3.  3.]]


In [15]:
# 각종 유용한 함수
a = np.array([-1,2,3,-4])
print(a)
a = np.abs(a)
print(a)

b = np.array([1,4,9])
print(b)
b = np.sqrt(b)
print(b)

import math # math 패키지로부터 자연상수 e를 호출하기 위함
c = np.array([math.e, 1, 2])
print(c)
c = np.log(c)
print(c)

d = np.array([1.1, 1.5, 1.9])
print(np.floor(d)) # 내림
print(np.ceil(d)) # 올림
print(np.rint(d)) # 반올림

[-1  2  3 -4]
[1 2 3 4]
[1 4 9]
[ 1.  2.  3.]
[ 2.71828183  1.          2.        ]
[ 1.          0.          0.69314718]
[ 1.  1.  1.]
[ 2.  2.  2.]
[ 1.  2.  2.]


## array iteration

In [ ]:
a = np.array([1,2,3])
for x in a:
    print(x)

b = np.array([[1,2],[3,4],[5,6]])
for x in b:
    print(x)
for (x,y) in b:
    print(x * y)

## 합, 곱, 최소값, 최대값 등

In [ ]:
a = np.array([1,2,3,4,5])
# 합
print('sum')
print(a.sum())
print(np.sum(a))
# 곱
print('production')
print(a.prod())
print(np.prod(a))
# 최소값과 그의 index
print('min value and its index')
print(a.min())
print(a.argmin())
# 최대값과 그의 index
print('max value and its index')
print(a.max())
print(a.argmax())
# 평균과 표준편차
print('mean')
print(a.mean())
print('standard deviation')
print(a.std())

## Matrix transpose

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

In [ ]:
a_prime = a.T
print(a_prime)

In [ ]:
# How to transpose 1-dimensional vector
b = np.array([1,2,3,4])
print(b)

In [ ]:
# Transpose가 먹히지 않는다.
print(b.T)

In [ ]:
# 만약 행 벡터를 열 벡터로 변환하고 싶다면 (약간의 꼼수)
b_prime = b.reshape(-1,1)
print(b_prime)
print(b.shape, ' ==> ', b_prime.shape)

## Numpy tutorials
- Numpy에서 매우 많은 기능들을 제공합니다. 
- Numpy reference manual: http://docs.scipy.org/doc/numpy/reference/
- Numpy quick-start: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
- Stanford Univ.의 수업 내용에 있는 튜토리얼 번역: http://aikorea.org/cs231n/python-numpy-tutorial/#numpy-arrays
- 필요한 기능이 있을 때 googling!